### ISSUE TITLE
Add OptiType results to MultiQC

### ISSUE THREAD

**Issue by apeltzer** [nf-core/hlatyping#105]
Should / could be a nice little table or custom module - could also have a simple `samtools idxstats` output in the same to display mapping stats of the different libraries independent of the mapper being used.

**Comment by christopher-mohr** [comment]
Related to issue https://github.com/nf-core/hlatyping/issues/72 ?

**Comment by apeltzer** [comment]
Yeah goes down the same road, but if we add samtools idxstats one would get a bit more than just the optiType results in the end :-) 
Though I have to see if its easier to have a OptiType Module for MultiQC or just write some custom code + module later for a new release of MultiQC :-)

**Comment by apeltzer** [comment]
https://github.com/ewels/MultiQC/pull/1387
