### ISSUE TITLE
Clean up Tempalte branch

### ISSUE THREAD

**Issue by apeltzer** [nf-core/hlatyping#107]
https://nf-co.re/developers/sync#fixing-a-broken-template-branch

(I'm on it, though this pipeline had a extreme case. Template wasn't really having initial commits that were done using sync, as we've been playing with this pipeline in the very beginning). I've created a completely fresh TEMPLATE branch in this case, we need to merge this once using the commandline to `dev` now and then things should be clean / fine for the next tools / template sync PRs 👍🏻

**Comment by christopher-mohr** [comment]
@apeltzer Do we still need to do this?

**Comment by apeltzer** [comment]
No, this is now outdated!
