### ISSUE TITLE
Add yara indexing to the pipeline

### ISSUE THREAD

**Issue by szymonwieloch** [nf-core/hlatyping#112]
Hi!

This issue is related to this one: https://github.com/nf-core/hlatyping/issues/111

I would like to be able to run the pipeline using just a fasta file as a reference. Internally the pipeline should run the yara_indexer in the right way and produce all the indexes that are later used by OptiType. you would use it in the following way:

```
nextflow run nf-core/hlatyping --reference ref.fasta.gz
```

I believe that this solution would not only be the easiest for users, but I would also be the best documentation of the procedure used to generate index files.

**Comment by apeltzer** [comment]
We added a YARA index module for DSL2, which means there is going to be a YARA index possibility for the new planned release.

**Comment by christopher-mohr** [comment]
`YARA` indexing has been added to the pipeline with the DSL2 port. I would suggest to close this issue and make a new one for the possibility to provide a FASTA file as reference. This can then be implemented for `2.1`. What do you think @apeltzer?

**Comment by apeltzer** [comment]
Yes please
