### ISSUE TITLE
DSLv2ify the pipeline

### ISSUE THREAD

**Issue by apeltzer** [nf-core/hlatyping#115]
This will require making modules for the steps we need in the pipeline:

- [x] BWA Mem
- [ ] Yara
- [x] Samtools
- [x] OptiType
- [x] MultiQC 

Parts of this already handled upstream in nf-core/modules, new tools release 1.13 should do help a lot to make this possible in the next two days.

**Comment by apeltzer** [comment]
key word: `nf-core module create`

**Comment by rivera10** [comment]
https://github.com/nf-core/modules/pull/353
