### ISSUE TITLE
Clean up the temp folder 

### ISSUE THREAD

**Issue by joonan30** [nf-core/hlatyping#121]
Thanks for the tool. 

One quick question: is there a command or config to remove or clean up the temp folder (`work`)? 

I am running ~100 human samples so try to keep some disk space from multiple temp folders.

**Comment by joonan30** [comment]
I think this works for me https://github.com/nextflow-io/nf-hack18/issues/3

I added `cleanup=true` to config

```
// Global default params, used in configs
params {
  // Workflow flags
  input = ''
  single_end = false
  outdir = './results'
  publish_dir_mode = 'copy'
  bam = false
  input_paths = ''
  seqtype = 'dna'
  solver = 'glpk'
  enumerations = 1
  beta = 0.009
  //use this to combine accordingly for dna/rna samples
  base_index_path = "$baseDir/data/indices/yara"
  base_index_name = ''
  cleanup = true

```

**Comment by christopher-mohr** [comment]
Hi @joonan30, good to hear that this works for you! Can we close this issue or do you need any further assistance?
