### ISSUE TITLE
Getting unbound variable error in optitype(hlatyping) pipeline: Can someone help me 

### ISSUE THREAD

**Issue by varun171** [nf-core/hlatyping#125]
The exit status of the task that caused the workflow execution to fail was: 1

Error executing process > 'pre_map_hla (1)'

Caused by:
  Process `pre_map_hla (1)` terminated with an error exit status (1)

Command executed:

  yara_mapper -e 3 -t 6 -f bam yara/$baseDir/data/references unzipped_1.fastq unzipped_2.fastq > output.bam
  samtools view -@ 6 -h -F 4 -f 0x40 -b1 output.bam > mapped_1.bam
  samtools view -@ 6 -h -F 4 -f 0x80 -b1 output.bam > mapped_2.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.sh: line 2: baseDir: unbound variable

Work dir:
  /fusion/s3/varun-nextflow-working/scratch/150Rok5sWh0TRL/e8/b54a3bdbe673a4021273dc5cbbab4a

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by christopher-mohr** [comment]
Hi @varun171, which command did you use to start the pipeline?

**Comment by varun171** [comment]
Hi Christopher, I used following command.
nextflow run 'https://github.com/nf-core/hlatyping'
		 -name hungry_stallman
		 -params-file nf-150Rok5sWh0TRL.params.json
		 -with-tower
		 -r 1.2.0

**Comment by christopher-mohr** [comment]
It could be this [issue](https://github.com/nf-core/tools/pull/778). Which Nextflow version are you using?

**Comment by varun171** [comment]
I am using 21.04.0 build 5552.

**Comment by christopher-mohr** [comment]
Would it be possible for you to use Nextflow < 20.04 and check if it works?

**Comment by christopher-mohr** [comment]
Closed due to lack of feedback.
