### ISSUE TITLE
HLA reference: unclear release version

### ISSUE THREAD

**Issue by sven1103** [nf-core/hlatyping#29]
Currently, it is not documented anywhere, which version of the HLA reference is used. EBI releases [several versions](https://www.ebi.ac.uk/ipd/imgt/hla/docs/release.html) during the year. 

Also, in terms of reproducibility, it would be a nice feature, if the pipeline could be run given a user-defined release version of the HLA reference.

- [x] document the current reference version 
- [ ] provide an optional parameter for reference version and dynamically compute the indices
- [ ] provide a static default reference version

**Comment by sven1103** [comment]
Added some [documentation](https://github.com/nf-core/hlatyping/blob/master/docs/references.md) about the used HLA release.

**Comment by christopher-mohr** [comment]
The HLA reference which is provided is documented in the [usage.md](https://github.com/nf-core/hlatyping/blob/dev/docs/usage.md#hla-references). This is also used as default reference version. 

I will open a separate issue for adding the functionality to process "custom" references.
