### ISSUE TITLE
Null -- hla reference index

### ISSUE THREAD

**Issue by praveenbas** [nf-core/hlatyping#37]
When I try to run the following command. 

```
nextflow run -r dev nf-core/hlatyping  -profile singularity --reads ‘data/*_R{1,2}.fastq.gz’ --solver cbc --prefix HROC400 --max_memory 6.GB
```

Execution stop with the error message  

```Open failed on file /home-link/qeaba01/.nextflow/assets/nf-core/hlatyping/null.txt.size: "No such file or directory"
  yara_mapper: Error while opening reference file. 
```

workflow take null as the reference instead of DNA as default.

**Comment by sven1103** [comment]
@praveenbas would you mind providing the `.nextlfow.log` file please? You can insert it in `https://pastebin.com` and post the link here. Thanks!

**Comment by praveenbas** [comment]
https://pastebin.com/zpWFc7ge

**Comment by sven1103** [comment]
Thanks @praveenbas for pointing this out. The index location is not set, and should be `index = 'data/indices/yara/hla_reference_dna'`. I will fix this and push to `dev` right away

**Comment by praveenbas** [comment]
@sven1103 , Tested the pipeline, it works fine.

**Comment by sven1103** [comment]
Thanks @praveenbas for the feedback! I will close this as soon as the PR is merged!
