### ISSUE TITLE
Pipeline completed without hla_run_result.tsv file

### ISSUE THREAD

**Issue by giovianco** [nf-core/hlatyping#56]
I'm launching the follow command line: 

MacBook-Air-de-Juan:Test_1 JBH$ /Users/JBH/VHIO/Apps/nextflow run -r 1.0.0 nf-core/hlatyping --reads '/Users/JBH/VHIO/Data/*.bam' --bam --index data/indices/yara/hla_reference_dna -profile standard,docker --max_memory '7.GB' --max_cpus '2'
N E X T F L O W  ~  version 19.01.0
Launching `nf-core/hlatyping` [kickass_swartz] - revision: 41d7b6baf7 [1.0.0]
WARN: There's no process matching config selector: fastqc
=========================================
 nf-core/hlatyping v1.0.0
=========================================
WARN: Access to undefined parameter `readPaths` -- Initialise it to a default value eg. `params.readPaths = some_value`
Run Name       : kickass_swartz
Reads          : /Users/JBH/VHIO/Data/*.bam
Data Type      : Paired-End
File Type      : BAM
IP solver      : glpk
Enumerations   : 1
Beta           : 0.009
Prefix         : hla_run
Max Memory     : 7.GB
Max CP Us      : 2
Max Time       : 10d
Output dir     : ./results
Working dir    : /Users/JBH/VHIO/Tests/Test_1/work
Container      : nfcore/hlatyping:1.0.0
Pipeline Release: 1.0.0
Current home   : /Users/JBH
Current user   : JBH
Current path   : /Users/JBH/VHIO/Tests/Test_1
Script dir     : /Users/JBH/.nextflow/assets/nf-core/hlatyping
Config Profile : standard,docker
=========================================
BAM file format detected. Initiate remapping to HLA alleles with yara mapper.
[warm up] executor > local
[6f/389204] Submitted process > make_ot_config
[35/e19dfc] Submitted process > remap_to_hla (1)
[4f/a722ef] Submitted process > run_optitype (1)
[nf-core/hlatyping] Pipeline Complete
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
MacBook-Air-de-Juan:Test_1 JBH$ cd results/
MacBook-Air-de-Juan:results JBH$ ls
Documentation	config		pipeline_info

The cextflow.log file in here:

[nextflow.log](https://github.com/nf-core/hlatyping/files/2940713/nextflow.log)

What I'm doing wrong? 
Thank you!

**Comment by apeltzer** [comment]
Please use the newest release and report back:

`-r 1.1.4`

**Comment by giovianco** [comment]
It's working! Thanks a lot!
