### ISSUE TITLE
Plans on class II?

### ISSUE THREAD

**Issue by acrinklaw** [nf-core/hlatyping#67]
Any plans on implementing tools that can perform class II typing as well?

**Comment by apeltzer** [comment]
@christopher-mohr are there?

**Comment by christopher-mohr** [comment]
Class II typing will be part of OptiType 2 which is currently under development. I would suggest to use it in this pipeline when its released.

**Comment by acrinklaw** [comment]
Thanks for the response! I'm glad to hear there will be an OptiType 2. We currently have to rely on a combination of class I calls from OptiType and class II from other tools but the accuracy has been markedly lower for the non-OptiType results.

**Comment by gurpreet-bioinfo** [comment]
Hi @acrinklaw Do you have any recommendation for class II tools for hlatyping?

**Comment by acrinklaw** [comment]
We use either PHLAT (which has low accuracy) or HLA-HD (which has significant runtime)

**Comment by gurpreet-bioinfo** [comment]
Ok, thanks @acrinklaw !

**Comment by christopher-mohr** [comment]
I will close this for now but we will come back to this topic when OptiType 2 is available.
