### ISSUE TITLE
Remove --genome and igenomes config from this pipeline as it is not used

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [nf-core/hlatyping#70]
Hi,

I have used the following command for hlatyping on paired-end rna-seq data:

```
nextflow run nf-core/hlatyping \
-profile cfc \
--reads '*_R{1,2}_merged.fastq.gz' \
--genome GRCh38 \
--outdir $PWD \
-name rnaseq2hla \
-resume
```
I am getting following error with config and GRCh38:
```
N E X T F L O W  ~  version 19.10.0
Launching `nf-core/hlatyping` [QLVMB_rnaseq2hla] - revision: bf5d0c2d46 [master]
WARN: The access of `config` object is deprecated
The provided genome 'GRCh38' is not available in the iGenomes file. Currently the available genomes are GRCh37, GRCm38, TAIR10, EB2, UMD3.1, WBcel235, CanFam3.1, GRCz10, BDGP6, EquCab2, EB1, Galgal4, Gm01, Mmul_1, IRGSP-1.0, CHIMP2.1.4, Rnor_6.0, R64-1-1, EF2, Sbi1, Sscrofa10.2, AGPv3
```
For https://github.com/nf-core/rnaseq , GRCh38 is available, so I expected it for hlatyping pipeline too.

Please help.

Thanks.
Gurpreet

**Comment by ggabernet** [comment]
Hi Gurpreet,

thanks for opening this issue. The GRCh38 reference genome needs to be added to this pipeline, unfortunately we need to add the references to each of the pipelines individually, in the `igenomes.config` https://github.com/nf-core/hlatyping/blob/master/conf/igenomes.config.

**Comment by gurpreet-bioinfo** [comment]
Hi Gisela,

Thank you for your reply.

Taking [this](https://gatk.broadinstitute.org/hc/en-us/articles/360035890951-Human-genome-reference-builds-GRCh38-or-hg38-b37-hg19) into account, I would like to use GRCh38. 

However, I don't know how much time-consuming it would be to add GRCh38. Do you think it can take quite a while? If so, I can go with GRCh37.

Thanks.
Gurpreet

**Comment by drpatelh** [comment]
Hi @ggabernet @gurpreet-bioinfo . I have updatesd the `igenomes.config` in the pipeline template to contain all relevant file paths for all nf-core pipelines. This just means we have to update this file in one place and the changes will be propagated to pipelines via the automated synchronisation when `nf-core tools` is released.

@gurpreet-bioinfo This means that this genome won't be available to the `hlatyping` pipeline until we have released `nf-core tools` but for now there may be a temporary fix. 

Can you try and download the file below and pass it to the pipeline using `--genome GRCh38 -c igenomes.config`. I don't know if it will work but it's worth a shot. 


Also, note that we haven't added the Ensembl GRCh38 assembly to AWS iGenomes yet so it's currently the NCBI version. If you are fine with that then it's ok, alternately you can use the `hg38` genome from the UCSC.

**Comment by ggabernet** [comment]
Hi Grupreet,

I just got the info from @christopher-mohr that the pipeline does not use the reference genome so far, but an internal HLA reference. Therefore, you can ignore the `--genome` parameter or just use for now `--genome GRCh37` with no difference.

I'll leave this issue though as either the updated reference should be used or the parameter removed from the pipeline to avoid confusions.

**Comment by ggabernet** [comment]
Thanks @drpatelh , adding it to the template is a great idea!

**Comment by gurpreet-bioinfo** [comment]
Thanks @drpatelh for fixing it for all nf-core pipelines. It will be very useful. 

Thanks @ggabernet for the clarification.

**Comment by ggabernet** [comment]
unnecessary param `--genome` has been removed so this is solved too!
