### ISSUE TITLE
parameters missing in docs toc

### ISSUE THREAD

**Issue by ggabernet** [nf-core/hlatyping#71]
Hi,

just to document this, there are some parameters missing in the docs. E.g. :

`--seqtype 'rna'`

**Comment by christopher-mohr** [comment]
Its documented here: https://github.com/nf-core/hlatyping/blob/master/docs/usage.md

**Comment by ggabernet** [comment]
Ah yeah, I didn't find it in the toc, so thought it was not there. Changed the issue name then! ;)

**Comment by ggabernet** [comment]
As the params are now in the nextflow schema anyways, this is no longer needed
