### ISSUE TITLE
Aggregate results from multiple samples

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [nf-core/hlatyping#72]
Hi there,

Is there any possibility to aggregate results from multiple samples of hlatyping output similar to what one gets as MultiQC report from rnaseq pipeline? Only software versions and workflow 
summary appear in MultiQC of hlatyping and no information about the analysis.

Off course, one can combine the tsv files from each folder (for each sample), but a way for comparative visualization would be great.

Thanks.
Gurpreet

**Comment by apeltzer** [comment]
It would be possible to create some [custom content](https://github.com/ewels/MultiQC/blob/master/docs/custom_content.md) for MultiQC and add this to the pipeline - Pull Requests / Feature implementations are always welcome here at nf-core :-)

**Comment by apeltzer** [comment]
(e.g. the nf-core/rnaseq pipeline does something similar like this with the biotypes stuff...)

**Comment by gurpreet-bioinfo** [comment]
@apeltzer  Thanks for the pointers. 
So far I managed by creating ggplot from multiple samples, but would look into [custom content](https://github.com/ewels/MultiQC/blob/master/docs/custom_content.md) too. :-)

**Comment by apeltzer** [comment]
Closing in favour of #105
