### ISSUE TITLE
configbuilder: command not found

### ISSUE THREAD

**Issue by pandyark** [nf-core/hlatyping#77]
I am using the offline version of hlatyping pipeline, when I run the pipeline using the following command in lsf script I get the error : .command.sh: line 2: configbuilder: command not found

**Command used to run the pipeline:**
nextflow run /nf-core-Pipelines/nf-core-hlatyping-1.1.5/workflow/ -profile singularity -with-singularity nf-core-Pipelines/nf-core-hlatyping-1.1.5/singularity-images/nf-core-hlatyping-1.1.5.img --singleEnd --bam --reads /exome/HLA-Typing/BAM_Files/*.bam' --fasta Analysis_Tools/Homo_sapiens_NCBI_GRCh38/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa --outdir 'exome/HLA-Typing/BAM_Files/results'

Error:
![image](https://user-images.githubusercontent.com/51807279/83182321-2ddacd80-a0f4-11ea-8ea1-66d8587680b4.png)

Any help will be appreciated!

**Comment by christopher-mohr** [comment]
Hi, this might be related to Singularity and it might not be able to find the container. Can you make sure that Singularity is working properly?

**Comment by christopher-mohr** [comment]
I guess we can close this due to missing feedback

**Comment by apeltzer** [comment]
Looks like a singularity issue indeed
