### ISSUE TITLE
Erorr running hlatyping with singularity

### ISSUE THREAD

**Issue by nvk747** [nf-core/hlatyping#88]
I am currently using Conda for next flow with following version:  
Version: 20.04.1 build 5335
  Created: 03-05-2020 19:37 UTC (15:37 EDT)
  System: Mac OS X 10.14.6
  Runtime: Groovy 2.5.8 on OpenJDK 64-Bit Server VM 11.0.1+13-LTS
  Encoding: UTF-8 (UTF-8)
When I run this command : 

 `(nextflow) lri-108040:hlatyping nagampv$ nextflow run ../hlatyping --input "/Users/nagampv/Desktop/nagampv_projects/SRR1200850_2_out.fastq.bam" --bam -profile singularity --outdir $PWD/test_results2` 

I am getting this error shown below. 

Container         : singularity - nfcore/hlatyping:1.1.5
Launch dir        : /Users/nagampv/Desktop/nagampv_projects/hlatyping
Script dir        : /Users/nagampv/Desktop/nagampv_projects/hlatyping
User              : nagampv
Config Profile    : singularity
[2m----------------------------------------------------
BAM file format detected. Initiate remapping to HLA alleles with yara mapper.
[-        ] process > remap_to_hla          -
[-        ] process > remap_to_hla          -
[-        ] process > remap_to_hla          -
[-        ] process > make_ot_config        -
[-        ] process > run_optitype          -
[-        ] process > output_documentation  -
[-        ] process > get_software_versions -
[-        ] process > multiqc               -
Pulling Singularity image docker://nfcore/hlatyping:1.1.5 [cache /Users/nagampv/Desktop/nagampv_projects/hlatyping/work/singularity/nfcore-hlatyping-1.1.5.img]
[0;35m[nf-core/hlatyping] Pipeline completed with errors
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /Users/nagampv/Desktop/nagampv_projects/hlatyping/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'make_ot_config'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name nfcore-hlatyping-1.1.5.img docker://nfcore/hlatyping:1.1.5 > /dev/null
  status : 127
  message:
    bash: singularity: command not found

Appears like my command cannot pull singularity image. The same command works well with -profile docker
any suggestions ?

**Comment by apeltzer** [comment]
> bash: singularity: command not found

You need to install singularity first ;-)

**Comment by nvk747** [comment]
Ohh i Thought it installs automatically 
if that is the case I will close the issue
